Unions of PlutusData and BuiltinData
OpShin/opshin pull request #397
Opened 2024-08-05 23:07 UTC by SCMusson

Targeting issue #367 
The following would now compile
```
source_code = """
from dataclasses import dataclass
from typing import Dict, List, Union
from pycardano import Datum as Anything, PlutusData

@dataclass()
class A(PlutusData):
    CONSTR_ID = 0
    foo: int

def validator(x: Union[A, int, bytes, List[int], Dict[int, int]]) -> int:
    k: int = 0
    if isinstance(x, A):
        k = 5
    elif isinstance(x, bytes):
        k = 7
    elif isinstance(x, int):
        k = 6
    elif isinstance(x, List[int]):
        k = 8
    elif isinstance(x, Dict[int, int]):
        k = 9
    return k
"""
```

I think it can't currently distinguish between `Dict[int, int]` and `Dict[int, bytes]` for example. I'll work on that if you think this is heading in the correct direction. I also need to sit down and think of what edge cases might break this and write some more tests.

2024-08-07 15:11 UTC, nielstron commented
I think it would be best to only allow joining Dict[Any, Any] and List[Any] in these unions, ideally making dict and list synonyms of this type.

If a user really knows what they are doing maybe an unsafe cast from dict to Dict[int, int] can then be allowed?

Also it's important that str is not allowed in these unions but this seems to be the case already.

What happens when a function has parameter type Union[A, int] and is passed an int/A (where the type of that variable was just int / A before)? Need to wrap in PlutusData in those cases

2024-08-07 15:15 UTC, nielstron commented on opshin/fun_impls.py
> +                    plt.Bool(True),
I like the take on isinstance as a polymorphic impl.

Is this enough though to ensure some x is the correct record type and not just any record type? isinstance(x, B) should not always return true for x of type Union[A, B]

2024-08-07 15:17 UTC, nielstron commented on opshin/type_inference.py
> +                if not v in ["List", "Dict"]
where does this come from?

2024-08-07 16:01 UTC, SCMusson commented on opshin/fun_impls.py
> +                    plt.Bool(True),
If there are both builtin and plutusData types in a union, then when checking plutusData it first checks its a record type and then invokes the old functionality of checking CONSTR_ID:
https://github.com/OpShin/opshin/blob/e0e5d25b7702c2f930f5719a5cf5826af4d01d46/opshin/type_inference.py#L962-L981

2024-08-07 16:06 UTC, SCMusson commented on opshin/type_inference.py
> +                if not v in ["List", "Dict"]
Neither List or Dict appear in `self.scopes` (so self.variable_type will fail) but end up in `externally_bound_vars`.  I'm not sure what the most 'correct' solution here is. I'm guessing there would be problems if someone tried to define there own class with the name `Test` and `Dict`.

2024-08-07 19:15 UTC, SCMusson commented
I've just realised too that `isinstance(x, List[int])` and `isinstance(x, Dict[int, int])` is not valid python.
The following would be thrown:

> TypeError: Subscripted generics cannot be used with class and instance checks


So would the following be what you are looking for:
 perhaps using `isinstance(x, list)` and `inisntance(x, dict)`.
```
source_code = """
from dataclasses import dataclass
from typing import Dict, List, Union
from pycardano import Datum as Anything, PlutusData

@dataclass()
class A(PlutusData):
    CONSTR_ID = 0
    foo: int

def validator(x: Union[A, int, bytes, List[Anything], Dict[Anything, Anything]]) -> int:
    k: int = 0
    if isinstance(x, A):
        k = 5
    elif isinstance(x, bytes):
        k = 7
    elif isinstance(x, int):
        k = 6
    elif isinstance(x, List):
        k = 8
    elif isinstance(x, Dict):
        k = 9
    return k
"""
``` 

Alternatively working towards using `isinstance(x, list)` and `isinstance(x, dict)` instead or as well as `isinstanec(x, List)` and `isinstance(x, Dict)`.

Let me know what you think.

2024-08-07 22:29 UTC, nielstron commented
Nice catch! If isinstance(x, Dict) is valid python that should be fine, otherwise isinstance(x, dict) would be required.

2024-08-18 14:57 UTC, SCMusson commented
I've had some free time so I've come back to this.
The following should run:
```
source_code = """
from dataclasses import dataclass
from typing import Dict, List, Union
from pycardano import Datum as Anything, PlutusData

@dataclass()
class A(PlutusData):
    CONSTR_ID = 0
    foo: int

def validator(x: Union[A, int, bytes, List[Anything], Dict[Anything, Anything]]) -> int:
    k: int = 0
    if isinstance(x, A):
        k = 5
    elif isinstance(x, bytes):
        k = 7
    elif isinstance(x, int):
        k = 6
    elif isinstance(x, List):
        k = 8
    elif isinstance(x, Dict):
        k = 9
    return k
"""
```
Only List[Anything] and Dict[Anything, Anything] are accepted in a Union now.
It will raise an error if List or Dict are subscripts inside isinstance to align with actual python.
Looks like python 3.11 CI errored because of timings not because of bugs from what I'm reading.

2024-08-23 08:24 UTC, nielstron requested changes
Looks great now. Just some small comments.

2024-08-23 08:24 UTC, nielstron commented on opshin/tests/test_Unions.py
> +    elif isinstance(x, list):
In order to make really sure that Python and OpShin map to the same operaton here (i.e. that List is allowed for isinstance)
```suggestion
    elif isinstance(x, List):
```

2024-08-23 08:24 UTC, nielstron commented on opshin/tests/test_Unions.py
> +    elif isinstance(x, dict):
```suggestion
    elif isinstance(x, Dict):
```

2024-08-23 08:24 UTC, nielstron commented on opshin/tests/test_Unions.py
> +class Union_tests(unittest.TestCase):
Please add a testcase that shows that Unioning PlutusData of the same constructors is illegal. Also one for str, bool (the non-allowed primitive type).

2024-08-23 10:50 UTC, SCMusson commented
Implemented those requested changes. 
Also test for failure with Bool, Str, and duplicate constr_ids in Unions. 
I added a check for duplicate constri_ids in Unions.

2024-08-24 07:24 UTC, nielstron approved these changes

2024-08-24 07:25 UTC, merged

2024-08-27 20:14 UTC, nielstron commented
As we have discovered a few missing edge cases here (see #403) I will not be able to pay out the full bug bounty for this PR. If @SCMusson is willing to supply the additional fixes I would simply offer additional time to resolve this and claim the full reward, otherwise we will have to decide a reasonable split with another developer.

2024-08-27 20:59 UTC, SCMusson commented
I plan to return to this problem, however I will be short of available time for the next week after which I will be able to devote some time to fixing this.

2024-08-27 21:59 UTC, nielstron commented
Sure, no problem 👍